data "terraform_remote_state" "gke" {
  backend = "local"

  config = {
    path = "../gke-cluster/terraform.tfstate"
  }
}

# Retrieve GKE cluster information
#provider "google" {
#  project = data.terraform_remote_state.gke.outputs.cluster_project_id
#  region  = data.terraform_remote_state.gke.outputs.cluster_region
#}

locals {
  instance_name      = data.terraform_remote_state.gke.outputs.instance_name
  environments       = data.terraform_remote_state.gke.outputs.cluster_environments
  project_id         = data.terraform_remote_state.gke.outputs.cluster_project_id
  region             = data.terraform_remote_state.gke.outputs.cluster_region
  main_zone          = data.terraform_remote_state.gke.outputs.cluster_main_zone
  cluster_network_id = data.terraform_remote_state.gke.outputs.cluster_network_id

  apigee_envgroups = {
    main = {
      name         = "${local.instance_name}-apigee-group"
      environments = local.environments
      hostnames    = ["main.api.example.com"]
    }
  }

  apigee_instances = {
    dev_qa_instance = {
      name         = "${local.instance_name}-apigee-instance"
      region       = local.region
      ip_range     = "10.0.0.0/22"
      environments = local.environments
    }
  }

}

resource "random_string" "autogenerated_apigee_db_name" {
  length  = 5
  numeric = false
  upper   = false
  special = false
}

module "apigee-x-core" {
  source = "../../../terraform-templates/gcp/apigee/apigee-x"

  apigee_name                 = local.instance_name
  project_id                  = local.project_id
  region                      = local.region
  main_zone                   = local.main_zone
  apigee_environments         = local.environments
  apigee_envgroups            = local.apigee_envgroups
  peer_network                = local.cluster_network_id
  apigee_instances            = local.apigee_instances
  apigee_org_kms_keyring_name = "" #"${local.environment}-apigee-db-${random_string.autogenerated_apigee_db_name.result}"
}
